version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sportivas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - sportivas-network

  db:
    image: postgres:15-alpine
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sportivas
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sportivas-network

networks:
  sportivas-network:
    driver: bridge

volumes:
  postgres-data: